# Generated by Django 3.0.7 on 2020-06-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20200609_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=25)),
                ('speed', models.FloatField()),
                ('vid_timestamp', models.FloatField()),
                ('user_id', models.CharField(max_length=12)),
                ('vid_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='usercount',
            name='user_id',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='videocount',
            name='vid_num',
            field=models.CharField(max_length=20),
        ),
    ]
